<?php

namespace AEncuesta\ModeloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConsultaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsultaRepository extends EntityRepository
{
}
