<?php

namespace Encuesta\ModeloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicoRepository extends EntityRepository
{
        public function findMedicoNombre($nombre) {
            $em = $this->getEntityManager();
            $consulta = $em->createQuery('
                      SELECT m FROM ModeloBundle:Medico m 
                                         
                    ');
            
            $medicos = $consulta->getResult();
            foreach($medicos as $medico) {
                if($medico->getNombreParaBusqueda() == $nombre)
                    return $medico;
            }
            
            return null;
        } 
}
