<?php

namespace Encuesta\ModeloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TurneroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurneroRepository extends EntityRepository
{
        public function findTurneroDia() {
            $em = $this->getEntityManager();
            $consulta = $em->createQuery('
                      SELECT t FROM ModeloBundle:Turnero t 
                      WHERE t.fecha LIKE :fecha            
                    ');
            $consulta->setParameter('fecha',  date('Ymd') );
            return $consulta->getOneOrNullResult();
        }      
}
