<?php

namespace Encuesta\ModeloBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TurnoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnoRepository extends EntityRepository
{
        public function findTurnosDia() {
            $em = $this->getEntityManager();
            $consulta = $em->createQuery('
                      SELECT t FROM ModeloBundle:Turno t 
                      WHERE t.fecha LIKE :fecha                    
                    ');
            $consulta->setParameter('fecha',  date('Ymd') );
            return $consulta->getResult();
        }   
        
        public function findCantidadTurnosDiaMarcados() {
            $em = $this->getEntityManager();
            $consulta = $em->createQuery('
                      SELECT t FROM ModeloBundle:Turno t 
                      WHERE t.fecha LIKE :fecha AND t.asistencia = true                  
                    ');
            $consulta->setParameter('fecha',  date('Ymd') );
            return count($consulta->getResult());
        }  
        
      
}
