jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Encuesta\ModeloBundle\Entity\Usuario: { algorithm: sha512, iterations: 5 }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        usuarios:
            entity: { class: Encuesta\ModeloBundle\Entity\Usuario, property: username }

    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
        dashboard:
            pattern: ^/
            provider:  usuarios
            anonymous: ~
            form_login:
                login_path: dashboard_login
                check_path: dashboard_login_check
                always_use_default_target_path: true
                default_target_path: dashboard_hompage
            logout:
                path: dashboard_logout
                target: /login
            remember_me:
                key: encuesta_dashboard
                lifetime: 3600        
            #fos_facebook:
                #app_url: "http://apps.facebook.com/appName/"
                #server_url: "http://localhost/facebookApp/"    

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/carga/turnos, roles: [ROLE_ADMIN] }        
        - { path: ^/usuario, roles: [ROLE_ADMIN] }        
        - { path: ^/*, roles: [ROLE_ADMIN, ROLE_USER] }
       
        #- { path: ^/, roles: [IS_AUTHENTICATED_ANONYMOUSLY, ROLE_USER] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
